Recon/Controllers/ApplyRuleController.cs
using System.Configuration;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;

using Recon_Model;
using System.Data;
using System.Net.Http;
using System.Net.Http.Headers;
using System.IO;
using Newtonsoft.Json;
using System.Text;
using System.Net;

namespace Recon.Controllers
{
    public class ApplyRuleController : Controller
    {
        CommonController objcommon = new CommonController();
        // string user_codes = ConfigurationManager.AppSettings["usercode"].ToString();
        string user_codes = System.Web.HttpContext.Current.Session["usercode"].ToString();
        //   string url = ConfigurationManager.AppSettings["URL"].ToString();
        //  string token = ConfigurationManager.AppSettings["token"].ToString();
        // GET: ApplyRule

        public ActionResult ApplyList()
        {
           //return RedirectToAction("ApplyList_New", "ApplyRule_New");
           return View();
        }

        public ActionResult ApplyRule()
        {
            return View();
        }
        public ActionResult ApplyRuleGrid_Read([DataSourceRequest]DataSourceRequest request, string slno)   // read grid dtl
        {
            try
            {
                ApplyRule_model ApplyRuleGrid = new ApplyRule_model();
                int listno = slno.Length;
                if (listno > 5)
                {
                    ApplyRuleGrid.slno = 0;
                }
                else
                {
                    ApplyRuleGrid.slno = Convert.ToInt32(slno);
                }
                ApplyRuleGrid.user_code = user_codes;
                List<ApplyRule_model> objcat_lst = new List<ApplyRule_model>();
                DataTable result = new DataTable();
                try
                {
                    string post_data = objcommon.getApiResult(JsonConvert.SerializeObject(ApplyRuleGrid), "Applyrulegriddtl");
                    result = (DataTable)JsonConvert.DeserializeObject(post_data, result.GetType());
                    for (int i = 0; i < result.Rows.Count; i++)
                    {
                        ApplyRule_model objcat = new ApplyRule_model();
                        objcat.slno = Convert.ToInt32(result.Rows[i][0]);
                        objcat.listslno = Convert.ToInt32(result.Rows[i][1]);
                        objcat.Rulegid = Convert.ToInt32(result.Rows[i][2]);
                        objcat.RuleName = result.Rows[i][3].ToString();
                        objcat.reversl_flag = result.Rows[i][4].ToString();
                        objcat.Ruleorder = result.Rows[i][5].ToString();
                        objcat.status = result.Rows[i][6].ToString();
                        objcat.status_desc = result.Rows[i][7].ToString();
                        objcat.sno = Convert.ToInt32(result.Rows[i][8]);
                        objcat.group_flag = result.Rows[i]["group_flag"].ToString();
                        objcat.group_method = result.Rows[i]["group_method"].ToString();
                        objcat.group_many = result.Rows[i]["manytomany_match_flag"].ToString();
                        objcat_lst.Add(objcat);
                    }
                    return Json(objcat_lst.ToDataSourceResult(request));
                }
                catch (Exception ex)
                {
                    string control = this.ControllerContext.RouteData.Values["controller"].ToString(); LogHelper.WriteLog(ex.ToString(), control);
                }
                return View();
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }

        public ActionResult ApplyRuleGrid_Readlist([DataSourceRequest]DataSourceRequest request)   // List  Read
        {
            ApplyRule_model ApplyRuleGrid = new ApplyRule_model();
            ApplyRuleGrid.slno = 0;
            ApplyRuleGrid.status = "";
            ApplyRuleGrid.user_code = user_codes;
            {
                List<ApplyRule_model> objcat_lst = new List<ApplyRule_model>();
                DataTable result = new DataTable();
                try
                {
                    string post_data = objcommon.getApiResult(JsonConvert.SerializeObject(ApplyRuleGrid), "ApplyruleList");
                    result = (DataTable)JsonConvert.DeserializeObject(post_data, result.GetType());
                    for (int i = 0; i < result.Rows.Count; i++)
                    {
                        ApplyRule_model objcat = new ApplyRule_model();
                        objcat.listslno = Convert.ToInt32(result.Rows[i]["applyrule_gid"]);
                        objcat.ReconName = result.Rows[i]["recon_name"].ToString();
                        objcat.Recontype = result.Rows[i]["recontype_desc"].ToString();
                        objcat.AccountnoRecName = result.Rows[i]["active_status_desc"].ToString();
                        objcat.supporting_file = result.Rows[i]["tranbrkptype_name"].ToString();
                        objcat_lst.Add(objcat);
                    }
                    return Json(objcat_lst.ToDataSourceResult(request));
                }
                catch (Exception ex)
                {
                    string control = this.ControllerContext.RouteData.Values["controller"].ToString(); LogHelper.WriteLog(ex.ToString(), control);
                }
                return View();
            }
        }
        public ActionResult ApplyRule_save(string Recontype, string recon_id, string matchsys, string matchman, string support_id, string period_from, string period_to, string untiflag, string status)   // Company  Read
        {

            {
                try
                {

                    ApplyRule_model ApplyRule = new ApplyRule_model();
                    ApplyRule.slno = 0;
                    ApplyRule.Recontype = Recontype;
                    ApplyRule.ReconName_id = Convert.ToInt32(recon_id);
                    ApplyRule.supporting_file_id = Convert.ToInt32(support_id);
                    ApplyRule.period_from = period_from;
                    if (period_to == "null")
                    {
                        period_to = null;
                    }
                    ApplyRule.period_to = period_to;
                    ApplyRule.matchoffSys = matchsys;
                    ApplyRule.status = status;
                    if (ApplyRule.matchoffSys == "")
                    {
                        ApplyRule.matchoffSys = "N";
                    }
                    ApplyRule.matchoffMan = matchman;
                    if (ApplyRule.matchoffMan == "")
                    {
                        ApplyRule.matchoffMan = "N";
                    }
                    ApplyRule.untillactive = untiflag;
                    if (ApplyRule.untillactive == "")
                    {
                        ApplyRule.untillactive = "N";
                    }
                    ApplyRule.user_code = user_codes;
                    string[] result = { };
                    string post_data = objcommon.getApiResult(JsonConvert.SerializeObject(ApplyRule), "ApplyruleCreate");
                    result = (string[])JsonConvert.DeserializeObject(post_data, result.GetType());
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {

                }
                return View();
            }
        }
        public ActionResult ApplyRule_Update(string Recontype, string recon_id, string matchsys, string matchman, string support_id, string period_from, string period_to, string untiflag, string slno, string status)   // Company  Read
        {
            {
                try
                {
                    ApplyRule_model ApplyRule = new ApplyRule_model();
                    ApplyRule.slno = Convert.ToInt32(slno);
                    ApplyRule.Recontype = Recontype;
                    ApplyRule.ReconName_id = Convert.ToInt32(recon_id);
                    ApplyRule.supporting_file_id = Convert.ToInt32(support_id);
                    ApplyRule.period_from = period_from;

                    ApplyRule.period_to = period_to;
                    ApplyRule.matchoffSys = matchsys;
                    ApplyRule.status = status;
                    if (ApplyRule.matchoffSys == "")
                    {
                        ApplyRule.matchoffSys = "N";
                    }
                    ApplyRule.matchoffMan = matchman;
                    if (ApplyRule.matchoffMan == "")
                    {
                        ApplyRule.matchoffMan = "N";
                    }
                    ApplyRule.untillactive = untiflag;
                    if (ApplyRule.untillactive == "")
                    {
                        ApplyRule.untillactive = "N";
                    }
                    string[] result = { };
                    string post_data = objcommon.getApiResult(JsonConvert.SerializeObject(ApplyRule), "ApplyruleUpdate");
                    result = (string[])JsonConvert.DeserializeObject(post_data, result.GetType());
                    ApplyRule.user_code = user_codes;
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    string control = this.ControllerContext.RouteData.Values["controller"].ToString();
                    LogHelper.WriteLog(ex.ToString(), control);
                }
                return View();
            }
        }
        public ActionResult ApplyRuleGrid_ReadAdd([DataSourceRequest]DataSourceRequest request, string slno = "0", string rulegid = "0")   // Addtional Condition
        {
            ApplyRule_model ApplyRuleGrid = new ApplyRule_model();
            int listno = slno.Length;
            if (listno > 3)
            {
                ApplyRuleGrid.slno = 0;

Recon/Views/ApplyRule_New/ApplyList_New.cshtml
@using Kendo.Mvc.UI;
@using Kendo.Mvc.UI.Fluent;
@using Kendo.Mvc.Extensions;
@using Kendo.Mvc.Resources;
@model Recon_Model.ApplyRule_model

<!Doctype html>
<html>
<head>
    <title></title>
    <style>
        .k-button.k-button-icontext.k-grid-add {
            background: green;
            color: white;
        }

        .k-pager-sizes {
            display: inline-flex !important;
            margin-left: 0% !important;
            margin-top: -4% !important;
            width: 24% !important;
        }
    </style>
    <style>
        .error_show {
            color: red;
            margin-left: 10px;
        }

        .k-state-active {
            display: none;
        }

        span.k-icon.k-filter {
            position: relative !important;
            top: 7px !important;
        }

        span.k-link {
            color: #fff !important;
        }

        a.k-button.k-button-icontext.k-grid-Edit, a.k-button.k-button-icontext.k-grid-View, a.k-button.k-button-icontext.k-grid-Delete {
            background: transparent;
            border-color: transparent;
        }

        .k-webkit {
            overflow: hidden !important;
        }
    </style>
</head>
<body class="hold-transition skin-blue sidebar-mini fixed">
    <div class="content-wrapper">
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-orange" style="height:auto;padding:10px">
                        <div class="box-header text-center with-border">
                            <h3 class="box-title">Apply Rule</h3>
                        </div>
                        @using (Html.BeginForm("ApplyList", "ApplyRule", FormMethod.Post, new { @id = "form1" }))
                        {
                            <div>
                                @*<a class="k-button k-button-icontext k-grid-add" href="../ApplyRule/ApplyRule"><span class="k-icon k-add"></span></a>*@
                                <a class="k-button k-button-icontext k-grid-add" style="width:3%" href="../ApplyRule_New/ApplyRule_New"><span>+</span></a>
                                @(Html.Kendo().Grid<Recon_Model.ApplyRule_model>().Name("ApplyList1")
                                    .HtmlAttributes(new { style = "width:100%;height:400px;line-height:2em;font-weight:normal" })
                                // .ToolBar(toolbar => toolbar.Create().Text(""))
                                    .Columns(columns =>
                                        {
                                            columns.Bound(m => m.ReconName).Title("Recon Name").Width(80);
                                            columns.Bound(m => m.Recontype).Title("Recon Type").Width(50);
                                            columns.Bound(m => m.supporting_file).Title("Supporting File").Width(50);

                                            //columns.Bound(m => m.Select).Title("Edit").ClientTemplate("<input type='checkbox'  #= Select == true ? checked='checked' : '' # />").Width(10);
                                            //columns.Template(p => { }).ClientTemplate("<a type='button' href='../ApplyRule/ApplyRule' class='k-button k-button-icontext '><span class='k-icon k-edit'></span>Edit</a>").Width(100).Title("Edit");
                                            columns.Command(command =>
                                            {
                                                command.Custom("Edit").Text("<span class='fa fa-pencil' style='color:#357ab8;font-size: 12px;'>").Click("editDetails");
                                                command.Custom("View").Text("<span class='fa fa-eye' style='color:#357ab8;font-size: 12px;'>").Click("viewDetails");
                                                command.Custom("Delete").Text("<span class='fa fa-trash' style='color:#357ab8;font-size: 12px;'>").Click("ApplyruleListdel");
                                            }).Title("Action").Width(30);
                                        })
                                    .Editable(editable =>
                                        { editable.Mode(GridEditMode.PopUp).TemplateName("ApplyRuleView_New"); })
                                    .Pageable(pageable => pageable
                                                .Refresh(true)
                                                .PageSizes(true)
                                                .ButtonCount(5))
                                    .Filterable()
                                    .Sortable()
                                    .Scrollable()
                                    .Resizable(resize => resize.Columns(true))
                                    .DataSource(dataSource => dataSource
                                    .Ajax()
                                    .PageSize(10)
                                        //.Events(events => events.Error("error_handler"))
                                    .Model(model => model.Id(p => p.Accountmode))

                                    .Read(read => read.Action("ApplyRuleGrid_Readlist", "ApplyRule_New"))

                                    ))
                            </div>
                        }
                    </div>
                </div>
            </div>
        </section>
    </div>
</body>
</html>

<script type="text/javascript">
    function error_handler(e) {
        if (e.errors) {
            var message = "Errors:\n";
            $.each(e.errors, function (key, value) {
                if ('errors' in value) {
                    $.each(value.errors, function () {
                        message += this + "\n";
                    });
                }
            });
            $.alert({
                title: 'Impact',
                content: message,
                type: 'red',
            });
        }
    }

    $(document).ready(function () {

        $("#tabs1").tabs();
        $("#ApplyList1").data("kendoGrid").dataSource.bind("requestEnd", onRequestEnd);
        var grid = $("#ApplyList1").data("kendoGrid");
        //function for changing kendo popup title.
        grid.bind("edit", function (event) {
            event.container.parent().find('.k-window-title').text(event.model.isNew() ? "New" : "Edit");
        });
    });
    function editDetails(e) {
        debugger
      
        var dataItem = this.dataItem($(e.target).closest("tr"));
        var id = dataItem.listslno;
        location.href = "@Url.Action("", "ApplyRule_New/ApplyRule_New")?Id=" + id
    }
    function viewDetails(e) {
        debugger;
        var dataItem = this.dataItem($(e.target).closest("tr"));
        var id = dataItem.listslno;
        location.href = "@Url.Action("", "ApplyRule_New/ApplyRule_New")?Id=?View=" + id
    }
    function onRequestEnd(e) {
        //Check request type
        if (e.type == "create") {
            //check for errors in the response
            if (e.response == null || e.response.Errors == null) {
                $.dialog({
                    title: 'Impact',
                    content: '',
                    type: 'green',
                });
                setTimeout(function () {

                    window.location.reload(1);
                }, 2000);

            }
        }
        if (e.type == "update") {
            //check for errors in the response
            if (e.response == null || e.response.Errors == null) {
                $.dialog({
                    title: 'Impact',
                    content: '',
                    type: 'green',
                })
                setTimeout(function () {

                    window.location.reload(1);
                }, 2000);
            }
        }
    }

    function ApplyruleListdel() {
        debugger;
        var grid = $("#ApplyList1").data("kendoGrid");
        var model = grid.dataItem($(event.target).closest("tr"));
        var listslno = (model.listslno);
        $.confirm({
            icon: 'fa fa-warning',
            title: 'Impact',
            autoClose: 'cancel|10000',
            animationSpeed: 700,
            content: 'Are you sure to delete ?',
            type: 'red',
            buttons: {
                confirm: function () {
                    $.ajax({
                        type: "POST",
                        contentType: "application/json; charset=utf-8",
                        async: false,
                        url: '@Url.Action("ApplyRulelist_Delete", "ApplyRule_New")',
                        data: "{ listslno:'" + listslno + "'}",
                        success: function (response) {
                            if (response[1] > 0) {
                                $.alert({
                                    icon: 'fa fa-success',
                                    title: 'Impact',
                                    content: response[0],
                                    type: 'blue',
                                    animationSpeed: 700,
                                });
                                setTimeout(function () {
                                    window.location.reload(1);
                                }, 2000);
                            }
                            else {
                                $.alert({
                                    icon: 'fa fa-success',
                                    title: 'Impact',
                                    content: response[0],
                                    type: 'blue',
                                    animationSpeed: 700,
                                });
                                preventCloseOnSave = true;
                            }
                        },
                    });
                },
                cancel: function () {
                    $.alert({
                        icon: 'fa fa-success',
                        title: 'Impact',
                        content: 'Delete cancelled !',
                        type: 'blue',
                        animationSpeed: 700,
                    });
                },
            }
        });
    }
</script>

Recon/Views/ApplyRule_New/EditApplyruleBaseFilter_New.cshtml
@model Recon_Model.ApplyRule_model
<style>
    div.k-window {
        display: inline-block;
        position: absolute;
        z-index: 10001;
        border-style: solid;
        border-width: 1px;
        padding-top: 1em;
        width: 80%;
        font-weight: normal;
    }



    .k-edit-form-container {
        position: relative;
        width: 80%;
    }


    .ui-autocomplete {
        z-index: 2147483647;
        max-height: 150px;
        overflow-x: hidden;
        padding-right: 20px;
    }

    li.ui-menu-item {
        font-size: 12px !important;
        /* font-family: Helvitica, serif; */
        font-weight: 600;
    }

        li.ui-menu-item:hover {
            font-size: 12px !important;
            /* font-family: Helvitica, serif; */
            font-weight: 600;
        }
</style>
<div class="container">
    @Html.HiddenFor(model => model.extraction_filter)
    @Html.HiddenFor(model => model.slnobase)
    <input class="text-box single-line" id="slnoadd" name="slnoadd" type="hidden" value="" data-bind="value:slnoadd" readonly>
    <input type="hidden" id="listslno1" name="listslno" value="">
    <input type="hidden" id="slno4" name="slno" value="">
    <input type="hidden" id="applyruledtl_gid1" name="applyruledtl_gid" value="">
    @* <input id="extraction_filter" name="extraction_filter" type="hidden">*@
    <input id="comparision_filter" name="comparision_filter" type="hidden">
    <input id="slnorule" name="comparision_filter" type="hidden">
    @Html.HiddenFor(model => model.slnobaseFilter, new { @style = "", @readonly = "readonly" })
    @Html.HiddenFor(model => model.slnobaseFilter, new { @style = "", @readonly = "readonly" })
    <div class="row" style="margin-left:-6%;">

      
        <div class="col-sm-3" style="width:23%;">
            <label for="" class="form-label">Filter Apply On</label>
            <div>
                @(Html.Kendo().DropDownList()
                                    .Name("applyfilter_code")
                                    .DataTextField("applyfilter_desc")
                                    .DataValueField("applyfilter_code")
                        //.Events(e => e.Change("onfieldchange1").DataBound("dbaliasname1"))
                            .HtmlAttributes(new { style = "" })
                                    .DataSource(source => { source.Read(read => { read.Action("DropDownBinding", "ApplyRule_New", new { dropdown = "applyfilteron", param_1 = "" }).Data("getbaseseleid"); }).ServerFiltering(true); }))

            </div>
        </div>
        <div class="col-sm-2" style="width:15%;">
            <label for="" class="form-label">Field Name</label>
            <div>
                @(Html.Kendo().DropDownList()
                            .Name("field_name")
                            .DataTextField("field_alias_name")
                            .DataValueField("field_name")
                            .Events(e => e.Change("onfieldchange1").DataBound("dbaliasname1"))
                                            .HtmlAttributes(new { style = "" })
                            .DataSource(source => { source.Read(read => { read.Action("dedupDbaliasdrop", "DedupeRule"); }).ServerFiltering(true); }))

            </div>
            </div>
            <div class="col-sm-2">
            <label for="" class="form-label">Status</label>
            <div>
                <input type="radio" id="status4_Act" name="statusActive" value="Y" checked> Active
                <input type="radio" id="status4_InAct" name="statusActive" value="N" style="margin-left: 10px;"> InActive
            </div>
                </div>
        </div>
    <div class="row">

       
        <div class="col-sm-2" id="extractvisiable" style="margin-left:62%;margin-top:-50px;">
            <label for="" class="form-label">Extraction Filter</label>
            <div>
                <form id="extractionfilter" style="width:243px;height:100px;overflow-y:scroll;margin-left:-46px;">
                    <div id="extractionfilter" class="k-listview">  </div>
                </form>
            </div>

        </div>
    </div>
    <div class="row" style="margin-top:10px;">
        <div class="col-sm-3" style="margin-top:-5%;margin-left:-56px;width:28%;">
            <label for="" class="form-label">Extraction Criteria</label>
            <input class="form-control" id="BaseCriteria" name="BaseCriteria" type="text" value="" data-bind="value:BaseCriteria">
        </div>
        <div class="col-sm-2" style="margin-left:263px;margin-top:-59px;width:18%;">
            <label for="" class="form-label">Identifier Criteria</label>
            <input class="form-control" id="Identitycriteria" name="Identitycriteria" type="text" value="" data-bind="value:Identitycriteria">

        </div>
        <div class="col-sm-2" style="margin-left:486px;margin-top:-59px;">
            <label for="" class="form-label">Identifier Value</label>
            <input class="form-control" id="TargetField" name="TargetField" type="text" value="" data-bind="value:TargetField">
        </div>
        <div class="col-sm-2" hidden>
            @Html.Label("Comparison Criteria", new { style = "font-size: 14px;font-weight: 600 !important;" })  <br />

            @*  @Html.TextBoxFor(model => model.ComparisonCriteria, new { @style = "" })*@
            @*<input id="ComparisonCriteria" type="text" name="ComparisonCriteria">*@
            @Html.TextBoxFor(model => model.ComparisonCriteria, new { @style = " " })
        </div>
        
        <div class="col-sm-2" style="margin-top:1%;margin-left:-50px;">
            <!--<input type="button" class="btn btn-orange" value="Update" id="btn_submit" onclick="SaveAdditionalRule()" class="btnsubmit" />-->
            <button type="button" class="btn btn-orange" value="Update" id="btn_submit1" onclick="SaveBaseFilterRule(this)"><i class="fa fa-refresh" aria-hidden="true"></i>&nbsp;Save</button>
            <!--<input type="button" class="btn btn-orange" value="Close" id="btn_Close" onclick="return CloseAddPopup();" class="btnsubmit" />-->

        </div>
    </div>
</div>